services:

  postgres:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_PASSWORD: password1234
    volumes:
      - ./infrastructure/db:/docker-entrypoint-initdb.d/
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080

  # php:
  #   build: ./php-container
  #   working_dir: /var/www/html
  #   restart: always
  #   volumes:
  #     - ./php-container/src:/var/www/html/
  #     - ../auth:/var/www/html/auth
  #     - ../frontend:/var/www/html/frontend
  #     - ../tc-report:/var/www/html/tc-report
  #   ports:
  #     - 8000:80
  #     - 8001:443
  #   env_file:
  #     - ../frontend/admin/.apache_env

  # maintenance:
  #   build: ./maintenance-container
  #   working_dir: /root/scripts
  #   deploy:
  #     mode: replicated
  #     replicas: 0
  #   volumes:
  #     - maintenancedata:/root
  #     - ../maintenance/scripts:/root/scripts
  #     - ../api:/var/www/html/api
  #     - ../auth:/var/www/html/auth
  #     - ../frontend:/var/www/html/frontend
  #     - ../tc-report:/var/www/html/tc-report

  api:
    build: ./api
    depends_on:
      - postgres
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/vendor
      - /usr/src/api/bootstrap/cache
      - /usr/src/api/storage/app/framework
      - /usr/src/api/storage/framework/cache/data
      - /usr/src/api/storage/framework/views
      - /usr/src/api/storage/logs
    ports:
      - 8002:8002
