services:

  postgres:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_PASSWORD: password1234
    volumes:
      - ./infrastructure/db:/docker-entrypoint-initdb.d/
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/frontend
      - shared:/usr/src/frontend/shared
      - /usr/src/frontend/node_modules
    env_file:
      - ./frontend/admin/.apache_env
    depends_on:
      - api
    #entrypoint: ["tail", "-f", "/dev/null"]

  reverseproxy:
    build: ./infrastructure/reverseproxy
    ports:
      - 8000:80
      - 8001:443
    volumes:
      - ./infrastructure/reverseproxy/src:/var/www/html/
      - ./tc-report:/var/www/html/tc-report
      - ./frontend/talentsearch:/var/www/html/frontend/talentsearch
      - ./frontend/admin:/var/www/html/frontend/admin
      - ./frontend/indigenousapprenticeship:/var/www/html/frontend/indigenousapprenticeship
      - ./api:/var/www/html/api
      - ./auth:/var/www/html/auth

  api:
    build: ./api
    depends_on:
      - postgres
    volumes:
      - ./api:/usr/src/api
      - shared:/usr/src/api/shared
      #todo: any way to clean these up?
      - /usr/src/api/vendor
      - /usr/src/api/bootstrap/cache
      - /usr/src/api/storage/app/framework
      - /usr/src/api/storage/framework/cache/data
      - /usr/src/api/storage/framework/views
      - /usr/src/api/storage/logs
    ports:
      - 8002:8002
    #entrypoint: [ "php", "artisan", "serve", "--host=0.0.0.0", "--port=8002" ]

  auth:
    build: ./auth
    depends_on:
      - postgres
    volumes:
      - ./auth:/usr/src/auth
      - shared:/usr/src/auth/shared
      #todo: any way to clean these up?
      - /usr/src/auth/node_modules
      - /usr/src/auth/vendor
      - /usr/src/auth/bootstrap/cache
      - /usr/src/auth/storage/app/framework
      - /usr/src/auth/storage/framework/cache/data
      - /usr/src/auth/storage/framework/views
      - /usr/src/auth/storage/logs
    ports:
      - 8003:8003
    #entrypoint: [ "php", "artisan", "serve", "--host=0.0.0.0", "--port=8003" ]

volumes:
  shared:
